// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGhTwdsfQzk7gbxrN6v4272CjBbYQiCzg',
    appId: '1:970045678864:web:6bb7035da5d789d1797195',
    messagingSenderId: '970045678864',
    projectId: 'sikreto-7cb85',
    authDomain: 'sikreto-7cb85.firebaseapp.com',
    storageBucket: 'sikreto-7cb85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPCxmC6VcsCPQNZ2C84gJJnUCT8wlfM2I',
    appId: '1:970045678864:android:68481dd607ef1ad5797195',
    messagingSenderId: '970045678864',
    projectId: 'sikreto-7cb85',
    storageBucket: 'sikreto-7cb85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb3j0iesTrdQ-eX5whG3kaiv2V21CIV-4',
    appId: '1:970045678864:ios:f05c576dadb91176797195',
    messagingSenderId: '970045678864',
    projectId: 'sikreto-7cb85',
    storageBucket: 'sikreto-7cb85.appspot.com',
    iosClientId: '970045678864-4p9r56d62nbq3bf1ht2jdheoi8vuqrsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sikreto',
  );
}
